# Generated by Django 4.2.7 on 2023-12-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdditionalCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_speed", models.PositiveSmallIntegerField(default=100)),
                ("one_to_hundred", models.PositiveSmallIntegerField(default=5)),
                ("usage", models.PositiveSmallIntegerField(default=15)),
                ("engine_capacity", models.FloatField(default=1.6)),
                (
                    "engine_type",
                    models.TextField(
                        choices=[
                            ("Diesel", "Diesel"),
                            ("Gasoline", "Gasoline"),
                            ("Electro", "Electro"),
                            ("Gas", "Gas"),
                        ],
                        default="Gasoline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=10)),
                ("year_of_issue", models.PositiveSmallIntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/cars/categories"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="media/cars/cars_images")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="cars.category",
                    ),
                ),
                (
                    "characteristics",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cars.additionalcharacteristics",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="additionalcharacteristics",
            name="brand",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="cars.brand"
            ),
        ),
    ]
